version: '3.9'


services:
  app:
    build:
      context: .
    env_file:
      - .env
    container_name: django_app
    entrypoint: sh -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - 9999:8000
    depends_on:
      db:
        condition: service_healthy


  db:
    image: postgres:15.1-alpine
    expose:
      - 5432
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d referral"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s
